# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
      - actions

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x] #[10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master  
      env:
        GITHUB_TOKEN: ${{ secrets.github }}
        SONAR_TOKEN: ${{ secrets.sonarcloud }}
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.snyk }}
      with:
        command: monitor
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1 
      with:
        login-server: acraltug.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    # Docker build and push to a Azure Container registry (ACR)
    - run: |
       docker build . -t acraltug.azurecr.io/k8sdemo:${{ github.sha }} -f Dockerfile.prod
       docker push acraltug.azurecr.io/k8sdemo:${{ github.sha }}
    # Set the target AKS cluster.
    - uses: azure/aks-set-context@v1 
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' 
        cluster-name: swoaks01
        resource-group: altug
    # Create imagepullsecret for Azure Container registry (ACR)
    - uses: azure/k8s-create-secret@v1 
      with:
        container-registry-url: acraltug.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }} 
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }} 
        secret-name: acr-secret
        namespace: githubactionsdemo
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1 
      with:
        manifests: |
          kubernetes/demodeployment.yaml
          namespace: githubactionsdemo
        images: |
          acraltug.azurecr.io/k8sdemo:${{ github.sha }} 
        imagepullsecrets: |
          acr-secret
          namespace: githubactionsdemo
      