# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# workshop

name: Github Actions - Azure

on:
  push:
    branches:
      - master
      - dev
      - feature/*

jobs:
  build:
    env:
      workshop: started
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
